pipeline {
  agent none

  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        dir('multi-stage-multi-agent') {
          sh 'mvn clean'
          sh 'mvn compile'
          sh 'mvn install'
        }
      }
    }

    stage('Front-end') {
      when {
        expression { fileExists('frontend/package.json') }
      }
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        dir('frontend') {
          sh 'node --version'
          sh 'npm install'
          sh 'npm run build'
        }
      }
    }
  }
}
