pipeline {
  agent none

  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        dir('backend') { // Change 'backend' to the actual folder containing pom.xml
          sh 'mvn clean'
          sh 'mvn compile'
          sh 'mvn install'
        }
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        dir('frontend') { // Change 'frontend' to the actual folder containing package.json
          sh 'node --version'
          sh 'npm install'
          sh 'npm run build'
        }
      }
    }
  }
}
